In [16]:
import numpy as np
import astropy.coordinates as coords
import astropy.units as u

In [17]:
foo = np.arange(10)
foo2 = foo < 5

In [20]:
a = coords.SkyCoord(ra=1.0*u.degree,dec=1.0*u.degree)

In [28]:
foo = dict(a=np.arange(3),b=np.arange(3),c=np.arange(3))

In [29]:
foo.keys()

['a', 'c', 'b']

In [31]:
for i in foo.keys():
    print foo[i]

[0 1 2]
[0 1 2]
[0 1 2]
